### ISSUE TITLE
Cannot see transactions that have been marked as paid/recieved

### ISSUE THREAD

**Issue by thepushkarp** [darshanpatel44/Udhari#7]
Missing Feature: When a transaction has been marked as paid/received, it disappears.

Proposed Solution: A section of past transactions where one can see paid/received transactions would be quite helpful.

**Comment by ashutoshsingh05** [comment]
Thanks a lot for the valuable suggestions @thepushkarp 
We appreciate your feedback 😀

**Comment by ashutoshsingh05** [comment]
This issue can be closed safely.
